{ pkgs, categories }:let
  luaTablePrinter = cats: let
    luatableformatter = categorySet: let
      nameandstringmap = builtins.mapAttrs (name: value:
        if value == true then "${name} = true"
        else if value == false then "${name} = false"
        else "${name} = [[${builtins.toString value}]]"
      ) categorySet;
      resultList = builtins.attrValues nameandstringmap;
      resultString = builtins.concatStringsSep ", " resultList;
    in
    resultString;
    catset = luatableformatter cats;
    LuaTable = "{ " + catset + " }";
  in
  LuaTable;

  RCTable = luaTablePrinter categories;

  nixCats = pkgs.stdenv.mkDerivation {
    name = "nixCats";
    builder = let
      # This is the entire code of nixCats. it returns a table generated above.
      cats = builtins.toFile "nixCats.lua" "return ${RCTable}";
      # This is where the help file is generated.
      # First, here are the help tags.
      helptags = builtins.toFile "tags" "nixCats	nixCats.txt	/*nixCats*";
      # and the text for the help file.
      helpCats = builtins.toFile "nixCats.txt" ''
        =======================================================================================
        NIX CATEGORIES                                                       *nixCats*

        For help with the nix flake files, see :help birdee.flake

        nixCats: returns category names included by nix for this package 

        Use this to check if this neovim was packaged with 
        a particular category included:

            local cats = require('nixCats')
            if(cats.nix) then
                -- some stuff here
            end

        Checking a category that is not present rather than false,
        will still return false from this if statement.
        I.e. if nix was not a category you included a value true or false for,
        it would evaluate as if it was false.

        The nixCats "plugin" is just a table. 
        It is generated by the flake,
        and is the same as the table you provided to choose what 
        categories are included in each package in the flake.nix file.

        Using:

            :lua print(vim.inspect(require('nixCats')))

        will return something like this:
        {
            AI = true,
            bash = true,
            cmp = true,
            customPlugins = true,
            general = true,
            gitPlugins = true,
            java = false,
            kotlin = true,
            lspDebugMode = false,
            markdown = true,
            neonixdev = true,
            telescope = true,
            theBestCat = "says meow!!!",
            treesitter = true
        }

        Note: it also accepts strings.

        If you use this syntax,
            local cats = require('nixCats')
            if(cats.theBestCat) then
              print("true")
            end
        theBestCat will evaluate as true if it contains a string.
            local cats = require('nixCats')
            if(cats.theBestCat == true) then
              print("true")
            else
              print("false")
            end
        However, this will print false.

        Either way, dependencies included under vocal cats 
        will not be included. So don't go changing all true 
        values to "meow" it wont work.

        Use this fact as you wish.
        You could use it to pass information like port numbers or paths
        Or whatever else you want.

        It gets this string in nix by calling builtins.toString 
        on the thing you provided and then surrounding it in [[]]

        ----------------------------------------------------------------------------------------
        vim:tw=78:ts=8:ft=help:norl:
      '';
    in builtins.toFile "builder.sh" ''
      source $stdenv/setup
      mkdir -p $out/lua
      mkdir -p $out/doc
      cp ${cats} $out/lua/nixCats.lua
      cp ${helpCats} $out/doc/nixCats.txt
      cp ${helptags} $out/doc/tags
    '';
  };
in
nixCats
